#!/usr/bin/env bash
# Bootstrap a fully self-hosted LeasePlease backend (Supabase stack in Docker)
# for local development, and reconcile the roles/grants/migrations that the
# trimmed docker-compose.yml does not handle on its own.
#
# Usage:
#   ./scripts/selfhost-bootstrap.sh
#
# What it does (idempotent on a FRESH db volume):
#   1. Generates .env.local (keys, passwords, local URLs, local-AI config) if absent.
#   2. Starts Postgres, fixes Supabase role passwords.
#   3. Resets public/auth/storage schemas so GoTrue & Storage build them cleanly
#      (the supabase/postgres image pre-creates conflicting objects).
#   4. Grants the privileges GoTrue/Storage need, starts them.
#   5. Applies the app SQL migrations in order and creates storage buckets.
#   6. Starts kong (gateway) + rest.
#
# After it finishes, run the app against the local stack with:
#   bun run dev          # reads .env.local automatically (kong on :8000)
# and start a local AI (see AGENTS.md) so chat photo->task analysis works:
#   OLLAMA_HOST=0.0.0.0:11434 ollama serve
#   ollama pull "$AI_MODEL"
set -euo pipefail

cd "$(dirname "$0")/.."
ENV_FILE=".env.local"
DC() { docker compose --env-file "$ENV_FILE" "$@"; }
PSQL() { DC exec -T db psql -U postgres -d postgres "$@"; }

# --- 1. .env.local --------------------------------------------------------
if [[ ! -f "$ENV_FILE" ]]; then
  echo ">>> Generating $ENV_FILE"
  JWT_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
  KEYS="$(JWT_SECRET="$JWT_SECRET" node scripts/gen-keys.mjs)"
  ANON_KEY="$(echo "$KEYS" | sed -n 's/^ANON_KEY=//p')"
  SERVICE_ROLE_KEY="$(echo "$KEYS" | sed -n 's/^SERVICE_ROLE_KEY=//p')"
  POSTGRES_PASSWORD="localdevpass$(openssl rand -hex 4)"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/selfhost-bootstrap.sh — local self-hosted overrides.
VITE_SUPABASE_URL=http://localhost:8000
VITE_SUPABASE_PUBLISHABLE_KEY=$ANON_KEY
VITE_SUPABASE_PROJECT_ID=self-hosted
SUPABASE_URL=http://localhost:8000
SUPABASE_PUBLISHABLE_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
AI_PROVIDER=local
AI_BASE_URL=http://localhost:11434/v1
AI_MODEL=qwen2.5vl:7b
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=postgres
JWT_SECRET=$JWT_SECRET
SITE_URL=http://localhost:8080
GOTRUE_MAILER_AUTOCONFIRM=true
ANON_KEY=$ANON_KEY
SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
EOF
fi

# Load env (POSTGRES_PASSWORD etc.) for SQL below.
set -a; . "./$ENV_FILE"; set +a

wait_for() { # <desc> <sql-returning-non-empty-when-ready>
  local desc="$1" sql="$2" i
  echo -n ">>> waiting for $desc"
  for i in $(seq 1 60); do
    if [[ -n "$(PSQL -tAc "$sql" 2>/dev/null | tr -d '[:space:]')" ]]; then echo " ok"; return 0; fi
    echo -n "."; sleep 2
  done
  echo " TIMEOUT"; return 1
}

# --- 2. Postgres + role passwords ----------------------------------------
echo ">>> Starting db"
DC up -d db
wait_for "postgres" "SELECT 1"
PSQL -v ON_ERROR_STOP=1 <<SQL
ALTER ROLE authenticator          WITH LOGIN PASSWORD '${POSTGRES_PASSWORD}';
ALTER ROLE supabase_auth_admin    WITH LOGIN PASSWORD '${POSTGRES_PASSWORD}';
ALTER ROLE supabase_storage_admin WITH LOGIN PASSWORD '${POSTGRES_PASSWORD}';
SQL

# --- 3. Clean schemas + privileges ---------------------------------------
echo ">>> Resetting public/auth/storage schemas"
DC stop auth storage rest >/dev/null 2>&1 || true
PSQL -v ON_ERROR_STOP=1 <<SQL
DROP SCHEMA IF EXISTS public  CASCADE;
DROP SCHEMA IF EXISTS auth    CASCADE;
DROP SCHEMA IF EXISTS storage CASCADE;
CREATE SCHEMA public;
CREATE SCHEMA auth    AUTHORIZATION supabase_auth_admin;
CREATE SCHEMA storage AUTHORIZATION supabase_storage_admin;
GRANT ALL   ON SCHEMA public TO postgres, service_role;
GRANT USAGE ON SCHEMA public TO anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres, service_role;
-- Storage/GoTrue need to assume request roles and own/create their schema objects.
GRANT ALL ON DATABASE postgres TO supabase_storage_admin;
GRANT anon, authenticated, service_role TO supabase_storage_admin, supabase_auth_admin;
GRANT USAGE ON SCHEMA auth, storage TO anon, authenticated, service_role;
SQL

# --- 4. GoTrue + Storage --------------------------------------------------
echo ">>> Starting auth + storage"
DC up -d auth storage
wait_for "auth.users"      "SELECT to_regclass('auth.users')"
wait_for "storage.objects" "SELECT to_regclass('storage.objects')"
PSQL -v ON_ERROR_STOP=1 <<SQL
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA auth TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA storage TO authenticated, service_role;
SQL

# --- 5. App migrations + buckets -----------------------------------------
echo ">>> Applying app migrations"
DC exec -T db bash -c 'set -e; for f in $(ls /docker-entrypoint-initdb.d/migrations/*.sql | sort); do psql -U postgres -d postgres -v ON_ERROR_STOP=1 -q -f "$f" >/dev/null; done'
echo ">>> Creating storage buckets"
PSQL -v ON_ERROR_STOP=1 <<SQL
INSERT INTO storage.buckets (id, name, public) VALUES ('documents','documents',false)             ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('chat-attachments','chat-attachments',false) ON CONFLICT (id) DO NOTHING;
SQL

# --- 6. Gateway -----------------------------------------------------------
echo ">>> Starting kong + rest"
DC up -d kong
DC restart rest >/dev/null 2>&1 || DC up -d rest

echo ""
echo "Self-hosted Supabase is up:"
echo "  - API gateway (kong): http://localhost:8000"
echo "  - Postgres:           localhost:5432"
echo "Next: 'bun run dev' (app on :8080) and an Ollama server for local AI."
